FROM kalilinux/kali-rolling

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 python3-pip python3-venv \
    curl wget ca-certificates \
    gcc libpq-dev \
    dnsutils \
    nmap \
    nikto \
    gobuster \
    sqlmap \
    ffuf \
    wafw00f \
    whatweb \
    sslscan \
    whois \
    testssl.sh \
    netcat-openbsd \
    nuclei \
    chkrootkit \
    clamav \
    dnsenum \
    dnsrecon \
    enum4linux \
    hydra \
    impacket-scripts \
    lynis \
    rkhunter \
    smbclient \
    wordlists \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN python3 -m venv /opt/venv && \
    /opt/venv/bin/pip install --no-cache-dir -r requirements.txt

COPY app/ app/
COPY engine/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENV PATH="/opt/venv/bin:$PATH"

ENTRYPOINT ["/entrypoint.sh"]
